name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Install Node and NPM
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
      
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          npm install
      
      - name: Run the build
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

